[package]
name = "lst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rowan = "0.15"
nom = "7.1"
num_enum = "0.5"
thiserror = "1.0.32"
expect-test = "1.4"
