[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ungrammar = "1.16"
prettyplease = "0.1"
syn = "1.0"
heck = "0.4"
quote = "1.0"
